config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  
  resources :homes, only: [:index]
  resources :posts, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  # belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes
  has_many :comments
  has_one_attached :image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    posts_path
  end

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  
  private
      def sign_in_required
          redirect_to new_user_session_url unless user_signed_in?
      end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :sign_in_required, only: [:show]

  def index
    @posts = Post.all
  end

  def new
    @posts = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to posts_path
  end

  def post_params
    params.require(:post).permit(:place, :text, :image, :users_id).merge(users_id: current_user.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/index.haml
.home
  .home__left
    .home__left--upper
      .picture
      .picture
      .picture
    .home__left--center
      .picture
      .picture
      .picture
    .home__left--under
      .picture
      .picture
      .picture
  .home__right
    .home__right--upper
      .home__right--upper__logo TABISPO
      .home__right--upper__text 「旅の思い出を共有しよう」
      .home__right--upper__email メールアドレス
      .home__right--upper__input
      .home__right--upper__pass パスワード
      .home__right--upper__input
      -# .home__right--upper__btn ログイン
      = link_to 'ログイン', new_user_session_path, class: "home__right--upper__btn"
    .home__right--under
      .home__right--under__text アカウントをお持ちでないですか？
      -# .home__right--under__btn 新規作成
      = link_to '新規作成', new_user_registration_path, class: "home__right--under__btn"

  

app/views/homes/index.html.haml
.home
  .home__left
    .home__left--upper
      .picture
      .picture
      .picture
    .home__left--center
      .picture
      .picture
      .picture
    .home__left--under
      .picture
      .picture
      .picture
  .home__right
    .home__right--upper
      .home__right--upper__logo TABISPO
      .home__right--upper__text 「旅の思い出を共有しよう」
      .home__right--upper__email メールアドレス
      .home__right--upper__input
      .home__right--upper__pass パスワード
      .home__right--upper__input
      = link_to 'ログイン', new_user_session_path, class: "home__right--upper__btn"
    .home__right--under
      .home__right--under__text アカウントをお持ちでないですか？
      = link_to '新規作成', new_user_registration_path, class: "home__right--under__btn"

  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TABISPO
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/_header.html.haml
.head
  .head__left
    = link_to "TABISPO", posts_path, class: "head__left__logo"
  .head__right
    .head__right__icon
    = link_to "投稿する", new_post_path, class: "head__right__post"
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "head__right__logout"

app/views/posts/index.html.haml
.wrapper
  = render "header"

  .index
    .index__frame
      .index__frame__map
      .index__frame__photo
        - @posts.each do |posts|
          = image_tag posts.image, class: "index__frame__photo__data"

app/views/posts/new.html.haml
.wrapper
  .posts
    .posts__frame
      = form_for @posts do |f|
        .posts__frame--upper
          .posts__text place
          = f.text_field :place, class:"posts__input"
        .posts__frame--center
          .posts__text image
          = f.file_field :image, class: "posts__image__input"
        .posts__frame--lower
          .posts__text text
          = f.text_area :text, class: "posts__text__input"
        = f.submit "投稿する", class: "posts__frame__btn"

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>